# YAML for setting up a conda environment for
# the Titanic library
name: titanic
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - pandas
  - python>=3.8.2
  - pytest
  - pytest-cov
  - pylint
  - jupyter
  - scikit-learn